name: Generate Snake Game

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write  # recommended for GitHub Pages

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Shreelfaldu
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # branch that stores the rendered SVG
          build_dir: output      # folder containing the SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
